from_latest_tag = true
ignore_merge_commits = true
disable_changelog = false
disable_bump_commit = false
generate_mono_repository_global_tag = true
branch_whitelist = []
skip_ci = "[skip ci]"
skip_untracked = true
pre_bump_hooks = []
post_bump_hooks = []
pre_package_bump_hooks = []
post_package_bump_hooks = []

# ? Setting git hooks
[git_hooks]
[git_hooks.commit-msg]
path = ".githooks/git-commit-msg.sh"
[git_hooks.pre-push]
path = ".githooks/git-pre-push.sh"
[git_hooks.post-rewrite]
path = ".githooks/git-post-rewrite.sh"

[commit_types]
chore = { changelog_title = "", omit_from_changelog = true }

[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
repository = "common-workflows"
owner = "EvoFrame"
authors = [
  { signature = "Cyborg", username = "cyboooooorg" }
]

[bump_profiles]

[packages]