# Local repository workflow

name: Local Labeler

on:
  # Triggers the workflow on pull request events
  pull_request_target:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  labeler:
    uses: EvoFrame/common-workflows/.github/workflows/mngt-labeler.yml@main
    with:
      labeler-config: .github/labeler.yml
