# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Management Staler

on:
  # Let the workflow be callable from other workflows
  workflow_call:

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      - uses: actions/stale@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          # Stale configuration for issues
          stale-issue-label: "issue-stale"
          days-before-issue-stale: 30
          days-before-issue-close: 5
          stale-issue-message: "This issue is stale because it has been open 30 days with no activity. Remove stale label or comment or this will be closed in 5 days."
          close-issue-message: "This issue was closed because it has been stalled for 5 days with no activity."
          # Stale configuration for pull requests
          stale-pr-label: "pr-stale"
          days-before-pr-stale: 45
          days-before-pr-close: 10
          stale-pr-message: "This PR is stale because it has been open 45 days with no activity. Remove stale label or comment or this will be closed in 10 days."
          close-pr-message: "This PR was closed because it has been stalled for 10 days with no activity."
