# This workflow is supposed to be used to manage the PR labels based on the rules defined in the .github/labeler.yml file
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/labeler
name: PR Labeler

on:
  # Let the workflow be callable from other workflows
  workflow_call:
    inputs:
      labeler-config:
        type: string
        required: false
        description: "The path to the labeler configuration file"
        default: ".github/labeler.yml"

  # Triggers the workflow on pull request events
  pull_request_target:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  pr-labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Labeler
        uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: ${{ inputs.labeler-config }}
