# Local repository workflow

name: PR Labeler

on:
  # Triggers the workflow on a schedule
  schedule:
    - cron: "0 3 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  labeler:
    uses: EvoFrame/common-workflows/.github/workflows/reusables/mngt-pr-issues-staler.yml@main
